### ISSUE TITLE
No pagination on search for all media types

### ISSUE THREAD

**Issue by Rittersm** [dwegrzen/Plethora#1]
When searching for all media types there is no pagination offered for the individual media types and clicking on a category of media makes me submit another search for that specific media type.

**Comment by dwegrzen** [comment]
unfortunately the gem we're using doesn't allow pagination for movie and tv show results. music does allow pagination when doing a music specific search. you can select a specific media type to search for in the search bar if you'd like. clicking the media category from your index (or from a search result) takes you to your index of that specific type of media (away from the search result itself).
