### ISSUE TITLE
What do these buttons do?

### ISSUE THREAD

**Issue by marthix** [dwegrzen/Plethora#5]
I wasn't sure what the headphones icon button was doing.

**Comment by mldenne** [comment]
Ditto - it looks like the headphones and the eye do the same thing as the + and checkmark. Is there a plan for a future purpose?

**Comment by mldenne** [comment]
Oh wait, now I understand what the buttons do! They let you know if you have watched or listened to the thing in your list - okay, see my newly created issue.

**Comment by smithambera** [comment]
We've updated it so they change color, the icon changes, and the buttons now also have words in them. Oh, also, a notification pops up when you click! I'm also thinking about adding a recording of us explaining what the buttons do each time you click one. That seems necessary, right?
