### ISSUE TITLE
Eye and Headphone Icons

### ISSUE THREAD

**Issue by mldenne** [dwegrzen/Plethora#8]
Ok, now that I understand what these icons do, I can make a suggestion. Is there a way to make them change color or delete the + or checkmark if they have already viewed or listened to the item in their list? If not, then may I suggest you only add the icons after the item has been added to the person's list? 
Ultimate: Have a separate page showing all viewed or listened to items! :)

**Comment by smithambera** [comment]
We've updated it so they change color, the icon changes, and the buttons now also have words in them. Oh, also, a notification pops up when you click!
